### ISSUE TITLE
predictable mt_rand

### ISSUE THREAD

**Issue by D9ping** [smiegles/PHP-csrf-security-classes#1]
On this line https://github.com/smiegles/PHP-csrf-security-classes/blob/40178484a4158436e5158bc2fd1ad6190a61cc06/security.csrf.php#L92
Consider using:  openssl_random_pseudo_bytes   if available / function_exists.

**Comment by smiegles** [comment]
Hi,

I agree with you. I will fix this later today. Thanks for the tip!

Kind regards

**Comment by D9ping** [comment]
A Hex(base-16) string of binary is exactly 2 times as much data as binary.
So instead of:
 $key = substr(bin2hex(openssl_random_pseudo_bytes(128)), 0, 128);
do:
 $key = bin2hex(openssl_random_pseudo_bytes(64));
for a 128 characters hex tokon.
